### Criar programa (GIMP)
POST http://localhost:3000/my-softwares
Content-Type: application/json 

{
  "nome": "GIMP",
  "site": "https://www.gimp.org",
  "descricao": "GIMP é um editor de imagens gratuito e de código aberto.",
  "categoria": "UTILITARIO", 
  "gratuito": true,
  "comentarios": "Tem me ajudado bastante a editar imagens."
}
### Criar programa (LibreOffice)
POST http://localhost:3000/my-softwares
Content-Type: application/json

{
  "nome": "LibreOffice",
  "site": "https://www.libreoffice.org",
  "descricao": "LibreOffice é uma suíte de escritório gratuita e de código aberto.",
  "categoria": "UTILITARIO", 
  "gratuito": true,
  "comentarios": "Uso o LibreOffice para todas as minhas necessidades de escritório."
}

### Criar programa (VLC Media Player)
POST http://localhost:3000/my-softwares
Content-Type: application/json

{
  "nome": "VLC Media Player",
  "site": "https://www.videolan.org/vlc/",
  "descricao": "VLC é um reprodutor multimídia gratuito e de código aberto.",
  "categoria": "MULTIMIDIA", 
  "gratuito": true,
  "comentarios": "VLC é ótimo para reproduzir qualquer tipo de mídia."
}

### Pegar todos os my-softwares
GET http://localhost:3000/my-softwares

### Pegar um programa
GET http://localhost:3000/my-softwares/93

### Atualizar um programa
PUT http://localhost:3000/my-softwares/93
Content-Type: application/json

{
  "nome": "Nome Atualizado",
  "site": "https://www.siteatualizado.com",
  "descricao": "Descrição atualizada",
  "comentarios": "Comentário atualizado"
}

### Deletar um programa
DELETE http://localhost:3000/my-softwares/93


### Criar programa sem todas as propriedades básicas
POST http://localhost:3000/my-softwares
Content-Type: application/json

{
  "nome": "VLC Media Player",
  "site": "https://www.videolan.org/vlc/",
  "descricao": "VLC é um reprodutor multimídia gratuito e de código aberto.",
  "comentarios": "VLC é ótimo para reproduzir qualquer tipo de mídia."
}

### Tentar atualizar campos não atualizáveis
PUT http://localhost:3000/my-softwares/0
Content-Type: application/json

{
  "id": 230,
  "nome": "Nome Atualizado (230)",
  "site": "https://www.siteatualizado230.com",
  "descricao": "Descrição atualizada (230)",
  "comentarios": "Comentário atualizado (230)",
  "idUsuario": 123123,
  "inseridoEm": "2023-10-01T00:00:00Z"
}
