import type { Metadata } from "next";
import "./globals.css";
import Mensagens from "@/components/Mensagens";
import { MensagensProvider } from "@/contexts/ContextoMensagens";
import { AutenticacaoProvider } from "@/contexts/ContextoAutenticacao";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-br">
			<body className=" min-h-screen bg-gray-100">
				<MensagensProvider>
					<AutenticacaoProvider>
						<Mensagens />
						{children}
					</AutenticacaoProvider>
				</MensagensProvider>
			</body>
		</html>
	);
}
